"""
Operators module - Phase 2

Contains low-level operators organized by category:
- arithmetic.py: add, sub, mul, div, matmul, etc.
- activations.py: relu, gelu, sigmoid, tanh, softmax, etc.
- reductions.py: sum, mean, max, min, argmax, etc.
- shape.py: cat, stack, split, reshape, flip, roll, rot90, etc.
- indexing.py: gather, scatter, where, masked_fill, etc.
- convolution.py: conv1d, conv2d, conv3d
- normalization.py: layer_norm, batch_norm
- pooling.py: max_pool2d, avg_pool2d
- sorting.py: sort, argsort, topk, etc.
- linalg_ops.py: einsum, tensordot, diag, triu, tril, etc.
"""

# Activation functions
from .activations import swish  # alias for silu
from .activations import (
    elu,
    gelu,
    leaky_relu,
    log_softmax,
    relu,
    sigmoid,
    silu,
    softmax,
    tanh,
)

# Arithmetic operations
from .arithmetic import absolute  # aliases
from .arithmetic import arctan2  # numpy-style aliases
from .arithmetic import (  # Extended math functions
    abs,
    acos,
    acosh,
    add,
    angle,
    arccos,
    arccosh,
    arcsin,
    arcsinh,
    arctan,
    arctanh,
    asin,
    asinh,
    atan,
    atan2,
    atanh,
    bmm,
    copysign,
    cos,
    cosh,
    digamma,
    div,
    divide,
    erfc,
    exp,
    exp2,
    expm1,
    float_power,
    fmax,
    fmin,
    frexp,
    heaviside,
    hypot,
    i0,
    isneginf,
    isposinf,
    isreal,
    ldexp,
    lgamma,
    log,
    log1p,
    log2,
    log10,
    logaddexp2,
    matmul,
    mm,
    mul,
    multiply,
    neg,
    nextafter,
    pow,
    sin,
    sinc,
    sinh,
    sqrt,
    sub,
    tan,
    xlogy,
)

# Comparison operations
from .comparison import (  # Aliases
    allclose,
    eq,
    equal,
    ge,
    greater,
    greater_equal,
    gt,
    isclose,
    le,
    less,
    less_equal,
    lt,
    maximum,
    minimum,
    ne,
    not_equal,
)
from .conv1d import conv1d
from .conv3d import conv3d, conv_transpose3d

# Convolution operations (torch.* level)
# Must import before quick_ops to avoid module shadowing the convolution function
from .convolution import conv2d as _conv2d_impl  # Import conv2d from convolution.py module

# Indexing operations
from .indexing import (  # Extended indexing operations; Scatter extensions
    argwhere,
    diagonal_scatter,
    fill,
    index_add,
    index_copy,
    index_fill,
    index_put,
    index_select,
    isin,
    masked_fill,
    masked_select,
    nonzero,
    put,
    scatter,
    scatter_add,
    scatter_reduce,
    select_scatter,
    slice_scatter,
    take,
    take_along_dim,
    where,
)

# Linear algebra operations (torch.* level)
from .linalg_ops import (
    diag,
    diagonal,
    dot,
    einsum,
    inner,
    kron,
    outer,
    tensordot,
    trace,
    tril,
    triu,
    vdot,
)

# Reduction operations
from .reductions import (  # Extended reduction operations
    all,
    amax,
    amin,
    aminmax,
    any,
    argmax,
    argmin,
    cummax,
    cummin,
    histc,
    logcumsumexp,
    max,
    mean,
    median,
    min,
    mode,
    nanmean,
    nansum,
    prod,
    quantile,
    std,
    std_mean,
    sum,
    var,
    var_mean,
)

# Shape manipulation operations
from .shape import (  # Extended shape operations; Additional shape ops
    adjoint,
    block_diag,
    broadcast_tensors,
    cat,
    chunk,
    column_stack,
    combinations,
    concat,
    diag_embed,
    diagflat,
    dsplit,
    dstack,
    expand,
    flip,
    fliplr,
    flipud,
    gather,
    hsplit,
    hstack,
    moveaxis,
    movedim,
    narrow,
    ravel,
    repeat,
    repeat_interleave,
    roll,
    rot90,
    row_stack,
    select,
    split,
    split_with_sizes,
    stack,
    swapaxes,
    swapdims,
    t,
    tensor_split,
    tile,
    unbind,
    unflatten,
    unsafe_chunk,
    unsafe_split,
    unsafe_split_with_sizes,
    vsplit,
    vstack,
)

# Sorting and selection operations
from .sorting import argsort, kthvalue, msort, sort, topk, unique, unique_consecutive

conv2d = _conv2d_impl  # Assign to conv2d after potential shadowing

# Math utility functions
from .math_funcs import (  # In-place variants; New math functions
    addcdiv,
    addcmul,
    bitwise_left_shift,
    bitwise_right_shift,
    ceil,
    clamp,
    clamp_max,
    clamp_max_,
    clamp_min,
    clamp_min_,
    clip,
    clip_,
    count_nonzero,
    cumprod,
    cumsum,
    cumulative_trapezoid,
    deg2rad,
    deg2rad_,
    diff,
    fix,
    fix_,
    floor,
    floor_divide,
    fmod,
    frac,
    gcd,
    gcd_,
    gradient,
    is_same_size,
    is_signed,
    isfinite,
    isinf,
    isnan,
    lcm,
    lcm_,
    lerp,
    logical_and,
    logical_not,
    logical_or,
    logical_xor,
    logit,
    logit_,
    nan_to_num,
    nan_to_num_,
    negative_,
    rad2deg,
    rad2deg_,
    range_,
    reciprocal,
    remainder,
    round,
    rsqrt,
    rsub,
    sgn,
    sign,
    signbit,
    square,
    square_,
    subtract,
    trapezoid,
    trapz,
    tril_indices,
    triu_indices,
    true_divide,
    trunc,
    unravel_index,
    vander,
)

# Pooling operations
from .pooling import (
    adaptive_avg_pool1d,
    adaptive_max_pool1d,
    avg_pool1d,
    avg_pool2d,
    max_pool1d,
    max_pool2d,
)

# Quick one-liner operations
from .quick_ops import (  # New additions; In-place operations; Grid sampler; Histogram; Other; RNN functions; Matrix functions; NaN-aware operations; Strided operations; Scatter/Index operations; Linear algebra extensions; Special math functions; Additional in-place ops; Additional linear algebra; Range and view ops
    addbmm,
    addmm,
    addmv,
    addr,
    affine_grid_generator,
    alpha_dropout_,
    as_strided,
    as_strided_,
    as_strided_scatter,
    atleast_1d,
    atleast_2d,
    atleast_3d,
    baddbmm,
    bilinear,
    binomial,
    bitwise_and,
    bitwise_not,
    bitwise_or,
    bitwise_xor,
    broadcast_to,
    chain_matmul,
    cholesky_inverse,
    cholesky_solve,
    concatenate,
    conj,
    constant_pad_nd,
    convolution,
    corrcoef,
    cov,
    ctc_loss,
    dist,
    dropout_,
    embedding_renorm_,
    empty_permuted,
    empty_strided,
    erf,
    erf_,
    erfc_,
    erfinv,
    exp2_,
    feature_alpha_dropout_,
    feature_dropout,
    feature_dropout_,
    fill_,
    frobenius_norm,
    from_file,
    frombuffer,
    geqrf,
    ger,
    grid_sampler,
    grid_sampler_2d,
    grid_sampler_3d,
    gru,
    histogram,
    histogramdd,
    i0_,
    igamma,
    igammac,
    imag,
    index_put_,
    index_reduce,
    ldexp_,
    lobpcg,
    logaddexp,
    logdet,
    logsumexp,
    lstm,
    lu_solve,
    lu_unpack,
    masked_scatter,
    matrix_exp,
    matrix_power,
    max_pool1d_with_indices,
    mv,
    mvlgamma,
    nanmedian,
    nanquantile,
    negative,
    nonzero_static,
    norm_except_dim,
    nuclear_norm,
    numel,
    orgqr,
    ormqr,
    pinverse,
    polygamma,
    positive,
    range_func,
    real,
    relu_,
    renorm,
    rms_norm,
    rnn_relu,
    rnn_tanh,
    sinc_,
    slice_inverse,
    triangular_solve,
    view_as_complex,
    view_as_real,
    xlogy_,
)

__all__ = [
    # Arithmetic
    "add",
    "sub",
    "mul",
    "div",
    "matmul",
    "mm",
    "bmm",
    "pow",
    "sqrt",
    "exp",
    "log",
    "abs",
    "neg",
    "sin",
    "cos",
    "tan",
    "sinh",
    "cosh",
    "asin",
    "acos",
    "atan",
    "atan2",
    "asinh",
    "acosh",
    "atanh",
    "log2",
    "log10",
    "log1p",
    "expm1",
    "multiply",
    "divide",
    "absolute",
    "arcsin",
    "arccos",
    "arctan",
    "arctan2",
    "arcsinh",
    "arccosh",
    "arctanh",
    # Extended math functions
    "angle",
    "exp2",
    "sinc",
    "hypot",
    "copysign",
    "heaviside",
    "fmax",
    "fmin",
    "erfc",
    "lgamma",
    "digamma",
    "i0",
    "isreal",
    "isneginf",
    "isposinf",
    "float_power",
    "logaddexp2",
    "nextafter",
    "frexp",
    "ldexp",
    "xlogy",
    # Activations
    "relu",
    "gelu",
    "sigmoid",
    "tanh",
    "softmax",
    "log_softmax",
    "silu",
    "leaky_relu",
    "elu",
    "swish",
    # Reductions
    "sum",
    "mean",
    "max",
    "min",
    "argmax",
    "argmin",
    "var",
    "std",
    "prod",
    "all",
    "any",
    "amax",
    "amin",
    "aminmax",
    # Extended reductions
    "median",
    "mode",
    "quantile",
    "nanmean",
    "nansum",
    "std_mean",
    "var_mean",
    "cummax",
    "cummin",
    "logcumsumexp",
    "histc",
    # Shape manipulation
    "cat",
    "stack",
    "split",
    "chunk",
    "expand",
    "repeat",
    "tile",
    "repeat_interleave",
    "gather",
    "narrow",
    "select",
    "unbind",
    "roll",
    "flip",
    "fliplr",
    "flipud",
    "rot90",
    # Extended shape operations
    "ravel",
    "t",
    "adjoint",
    "moveaxis",
    "swapaxes",
    "hstack",
    "vstack",
    "dstack",
    "column_stack",
    "row_stack",
    "hsplit",
    "vsplit",
    "dsplit",
    "tensor_split",
    "block_diag",
    "diag_embed",
    "diagflat",
    # Additional shape ops
    "movedim",
    "swapdims",
    "broadcast_tensors",
    "unflatten",
    "concat",
    "combinations",
    "split_with_sizes",
    "unsafe_chunk",
    "unsafe_split",
    "unsafe_split_with_sizes",
    # Sorting and selection
    "sort",
    "argsort",
    "topk",
    "kthvalue",
    "msort",
    "unique",
    "unique_consecutive",
    # Linear algebra
    "einsum",
    "tensordot",
    "diag",
    "diagonal",
    "triu",
    "tril",
    "trace",
    "outer",
    "inner",
    "dot",
    "vdot",
    "kron",
    # Indexing
    "scatter",
    "scatter_add",
    "index_select",
    "where",
    "masked_fill",
    "masked_select",
    "index_add",
    "nonzero",
    "take",
    "put",
    # Extended indexing
    "index_fill",
    "index_copy",
    "index_put",
    "fill",
    "take_along_dim",
    "argwhere",
    "isin",
    # Comparison
    "eq",
    "ne",
    "lt",
    "le",
    "gt",
    "ge",
    "equal",
    "allclose",
    "isclose",
    "maximum",
    "minimum",
    "greater",
    "greater_equal",
    "less",
    "less_equal",
    "not_equal",
    # Math utilities
    "clamp",
    "clip",
    "clamp_min",
    "clamp_max",
    "clamp_min_",
    "clamp_max_",
    "clip_",
    "floor",
    "ceil",
    "round",
    "trunc",
    "frac",
    "fix",
    "fix_",
    "sign",
    "signbit",
    "isnan",
    "isinf",
    "isfinite",
    "logical_and",
    "logical_or",
    "logical_not",
    "logical_xor",
    "reciprocal",
    "rsqrt",
    "square",
    "lerp",
    "addcmul",
    "addcdiv",
    "fmod",
    "remainder",
    "cumsum",
    "cumprod",
    "deg2rad",
    "rad2deg",
    "deg2rad_",
    "rad2deg_",
    "nan_to_num",
    "nan_to_num_",
    "count_nonzero",
    "diff",
    # In-place variants
    "negative_",
    "square_",
    # New math functions
    "logit",
    "logit_",
    "sgn",
    "rsub",
    "subtract",
    "floor_divide",
    "true_divide",
    "gcd",
    "gcd_",
    "lcm",
    "lcm_",
    "trapezoid",
    "trapz",
    "cumulative_trapezoid",
    "gradient",
    "is_same_size",
    "is_signed",
    "vander",
    "unravel_index",
    "tril_indices",
    "triu_indices",
    "range_",
    "bitwise_left_shift",
    "bitwise_right_shift",
    # Quick ops
    "atleast_1d",
    "atleast_2d",
    "atleast_3d",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "bitwise_not",
    "broadcast_to",
    "concatenate",
    "conj",
    "erf",
    "erfinv",
    "negative",
    "positive",
    "real",
    "imag",
    "logaddexp",
    "logsumexp",
    "addmm",
    "baddbmm",
    "mv",
    "addr",
    "numel",
    # New quick ops
    "addbmm",
    "addmv",
    "chain_matmul",
    "dist",
    "corrcoef",
    "cov",
    "bilinear",
    "constant_pad_nd",
    "ger",
    "frobenius_norm",
    "frombuffer",
    "binomial",
    "convolution",
    "affine_grid_generator",
    # In-place operations
    "dropout_",
    "alpha_dropout_",
    "feature_alpha_dropout_",
    "erf_",
    "erfc_",
    "exp2_",
    "i0_",
    "fill_",
    # Grid sampler
    "grid_sampler",
    "grid_sampler_2d",
    "grid_sampler_3d",
    # Histogram
    "histogram",
    "histogramdd",
    # Other
    "feature_dropout",
    "igamma",
    "igammac",
    "polygamma",
    # RNN functions
    "lstm",
    "gru",
    # Matrix functions
    "logdet",
    "matrix_exp",
    "matrix_power",
    # NaN-aware operations
    "nanmedian",
    "nanquantile",
    # Strided operations
    "as_strided",
    "as_strided_",
    "as_strided_scatter",
    "empty_permuted",
    "empty_strided",
    "nonzero_static",
    # Scatter/Index operations
    "index_put_",
    "index_reduce",
    "masked_scatter",
    # Linear algebra extensions
    "cholesky_inverse",
    "cholesky_solve",
    "lu_solve",
    "lu_unpack",
    "geqrf",
    # Special math functions
    "mvlgamma",
    "ldexp_",
    "embedding_renorm_",
    "feature_dropout_",
    "from_file",
    "max_pool1d_with_indices",
    "ctc_loss",
    # Additional in-place ops
    "relu_",
    "sinc_",
    "xlogy_",
    # Additional linear algebra
    "pinverse",
    "triangular_solve",
    "nuclear_norm",
    "renorm",
    "norm_except_dim",
    # Range and view ops
    "range_func",
    "view_as_complex",
    "view_as_real",
    "rms_norm",
    "rnn_tanh",
    "rnn_relu",
    "slice_inverse",
    "orgqr",
    "ormqr",
    "lobpcg",
    # Pooling
    "max_pool2d",
    "avg_pool2d",
    "max_pool1d",
    "avg_pool1d",
    "adaptive_avg_pool1d",
    "adaptive_max_pool1d",
    # Convolution
    "conv1d",
    "conv2d",
    "conv3d",
    "conv_transpose3d",
]
