name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code to reproduce the issue.
      placeholder: |
        import flashlight as fl

        # Your code here
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: pytorch_comparison
    attributes:
      label: PyTorch Comparison (if parity issue)
      description: If this is a parity issue, provide equivalent PyTorch code and its output.
      placeholder: |
        import torch

        # Equivalent PyTorch code
      render: python

  - type: input
    id: python_version
    attributes:
      label: Python Version
      placeholder: "3.11"
    validations:
      required: true

  - type: input
    id: mlx_version
    attributes:
      label: MLX Version
      placeholder: "0.20.0"
    validations:
      required: true

  - type: input
    id: flashlight_version
    attributes:
      label: Flashlight Version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: macos_version
    attributes:
      label: macOS Version
      placeholder: "14.0 (Sonoma)"
    validations:
      required: true

  - type: input
    id: hardware
    attributes:
      label: Apple Silicon Chip
      placeholder: "M1 / M2 / M3 / M4"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
