name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: pytorch_equivalent
    attributes:
      label: PyTorch Equivalent
      description: If this feature exists in PyTorch, show how it works there.
      placeholder: |
        import torch

        # PyTorch equivalent
      render: python

  - type: textarea
    id: proposed_api
    attributes:
      label: Proposed API
      description: How do you envision this feature being used?
      placeholder: |
        import flashlight as fl

        # Proposed usage
      render: python

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area of the library does this relate to?
      options:
        - Tensor operations
        - Neural network layers (nn)
        - Autograd / gradients
        - Optimizers
        - Data loading
        - Performance
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR for this feature
